// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: sniperc/proto/geyserpb/geyser.proto

package geyserpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommitmentLevel int32

const (
	CommitmentLevel_PROCESSED CommitmentLevel = 0
	CommitmentLevel_CONFIRMED CommitmentLevel = 1
	CommitmentLevel_FINALIZED CommitmentLevel = 2
)

// Enum value maps for CommitmentLevel.
var (
	CommitmentLevel_name = map[int32]string{
		0: "PROCESSED",
		1: "CONFIRMED",
		2: "FINALIZED",
	}
	CommitmentLevel_value = map[string]int32{
		"PROCESSED": 0,
		"CONFIRMED": 1,
		"FINALIZED": 2,
	}
)

func (x CommitmentLevel) Enum() *CommitmentLevel {
	p := new(CommitmentLevel)
	*p = x
	return p
}

func (x CommitmentLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommitmentLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_sniperc_proto_geyserpb_geyser_proto_enumTypes[0].Descriptor()
}

func (CommitmentLevel) Type() protoreflect.EnumType {
	return &file_sniperc_proto_geyserpb_geyser_proto_enumTypes[0]
}

func (x CommitmentLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommitmentLevel.Descriptor instead.
func (CommitmentLevel) EnumDescriptor() ([]byte, []int) {
	return file_sniperc_proto_geyserpb_geyser_proto_rawDescGZIP(), []int{0}
}

type SubscribeRequestFilterTransactions struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Vote           bool                   `protobuf:"varint,1,opt,name=Vote,proto3" json:"Vote,omitempty"`
	Failed         bool                   `protobuf:"varint,2,opt,name=Failed,proto3" json:"Failed,omitempty"`
	AccountInclude []string               `protobuf:"bytes,3,rep,name=AccountInclude,proto3" json:"AccountInclude,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubscribeRequestFilterTransactions) Reset() {
	*x = SubscribeRequestFilterTransactions{}
	mi := &file_sniperc_proto_geyserpb_geyser_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequestFilterTransactions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequestFilterTransactions) ProtoMessage() {}

func (x *SubscribeRequestFilterTransactions) ProtoReflect() protoreflect.Message {
	mi := &file_sniperc_proto_geyserpb_geyser_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequestFilterTransactions.ProtoReflect.Descriptor instead.
func (*SubscribeRequestFilterTransactions) Descriptor() ([]byte, []int) {
	return file_sniperc_proto_geyserpb_geyser_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequestFilterTransactions) GetVote() bool {
	if x != nil {
		return x.Vote
	}
	return false
}

func (x *SubscribeRequestFilterTransactions) GetFailed() bool {
	if x != nil {
		return x.Failed
	}
	return false
}

func (x *SubscribeRequestFilterTransactions) GetAccountInclude() []string {
	if x != nil {
		return x.AccountInclude
	}
	return nil
}

type SubscribeRequest struct {
	state              protoimpl.MessageState                         `protogen:"open.v1"`
	Transactions       map[string]*SubscribeRequestFilterTransactions `protobuf:"bytes,1,rep,name=Transactions,proto3" json:"Transactions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TransactionsStatus map[string]*SubscribeRequestFilterTransactions `protobuf:"bytes,2,rep,name=TransactionsStatus,proto3" json:"TransactionsStatus,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Commitment         CommitmentLevel                                `protobuf:"varint,3,opt,name=Commitment,proto3,enum=sniperc.proto.CommitmentLevel" json:"Commitment,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_sniperc_proto_geyserpb_geyser_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sniperc_proto_geyserpb_geyser_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_sniperc_proto_geyserpb_geyser_proto_rawDescGZIP(), []int{1}
}

func (x *SubscribeRequest) GetTransactions() map[string]*SubscribeRequestFilterTransactions {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *SubscribeRequest) GetTransactionsStatus() map[string]*SubscribeRequestFilterTransactions {
	if x != nil {
		return x.TransactionsStatus
	}
	return nil
}

func (x *SubscribeRequest) GetCommitment() CommitmentLevel {
	if x != nil {
		return x.Commitment
	}
	return CommitmentLevel_PROCESSED
}

type SubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *TransactionUpdate     `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_sniperc_proto_geyserpb_geyser_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sniperc_proto_geyserpb_geyser_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_sniperc_proto_geyserpb_geyser_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeResponse) GetTransaction() *TransactionUpdate {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type InnerInstruction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instructions  []*Instruction         `protobuf:"bytes,1,rep,name=instructions,proto3" json:"instructions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InnerInstruction) Reset() {
	*x = InnerInstruction{}
	mi := &file_sniperc_proto_geyserpb_geyser_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InnerInstruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InnerInstruction) ProtoMessage() {}

func (x *InnerInstruction) ProtoReflect() protoreflect.Message {
	mi := &file_sniperc_proto_geyserpb_geyser_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InnerInstruction.ProtoReflect.Descriptor instead.
func (*InnerInstruction) Descriptor() ([]byte, []int) {
	return file_sniperc_proto_geyserpb_geyser_proto_rawDescGZIP(), []int{3}
}

func (x *InnerInstruction) GetInstructions() []*Instruction {
	if x != nil {
		return x.Instructions
	}
	return nil
}

type Meta struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	LoadedWritableAddresses [][]byte               `protobuf:"bytes,1,rep,name=loaded_writable_addresses,json=loadedWritableAddresses,proto3" json:"loaded_writable_addresses,omitempty"`
	LoadedReadonlyAddresses [][]byte               `protobuf:"bytes,2,rep,name=loaded_readonly_addresses,json=loadedReadonlyAddresses,proto3" json:"loaded_readonly_addresses,omitempty"`
	InnerInstructions       []*InnerInstruction    `protobuf:"bytes,3,rep,name=inner_instructions,json=innerInstructions,proto3" json:"inner_instructions,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Meta) Reset() {
	*x = Meta{}
	mi := &file_sniperc_proto_geyserpb_geyser_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meta) ProtoMessage() {}

func (x *Meta) ProtoReflect() protoreflect.Message {
	mi := &file_sniperc_proto_geyserpb_geyser_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meta.ProtoReflect.Descriptor instead.
func (*Meta) Descriptor() ([]byte, []int) {
	return file_sniperc_proto_geyserpb_geyser_proto_rawDescGZIP(), []int{4}
}

func (x *Meta) GetLoadedWritableAddresses() [][]byte {
	if x != nil {
		return x.LoadedWritableAddresses
	}
	return nil
}

func (x *Meta) GetLoadedReadonlyAddresses() [][]byte {
	if x != nil {
		return x.LoadedReadonlyAddresses
	}
	return nil
}

func (x *Meta) GetInnerInstructions() []*InnerInstruction {
	if x != nil {
		return x.InnerInstructions
	}
	return nil
}

type Instruction struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProgramIdIndex uint32                 `protobuf:"varint,1,opt,name=ProgramIdIndex,proto3" json:"ProgramIdIndex,omitempty"`
	Data           []byte                 `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	Accounts       []uint32               `protobuf:"varint,3,rep,packed,name=Accounts,proto3" json:"Accounts,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Instruction) Reset() {
	*x = Instruction{}
	mi := &file_sniperc_proto_geyserpb_geyser_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instruction) ProtoMessage() {}

func (x *Instruction) ProtoReflect() protoreflect.Message {
	mi := &file_sniperc_proto_geyserpb_geyser_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instruction.ProtoReflect.Descriptor instead.
func (*Instruction) Descriptor() ([]byte, []int) {
	return file_sniperc_proto_geyserpb_geyser_proto_rawDescGZIP(), []int{5}
}

func (x *Instruction) GetProgramIdIndex() uint32 {
	if x != nil {
		return x.ProgramIdIndex
	}
	return 0
}

func (x *Instruction) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Instruction) GetAccounts() []uint32 {
	if x != nil {
		return x.Accounts
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountKeys   [][]byte               `protobuf:"bytes,1,rep,name=account_keys,json=accountKeys,proto3" json:"account_keys,omitempty"`
	Instructions  []*Instruction         `protobuf:"bytes,2,rep,name=instructions,proto3" json:"instructions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_sniperc_proto_geyserpb_geyser_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_sniperc_proto_geyserpb_geyser_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_sniperc_proto_geyserpb_geyser_proto_rawDescGZIP(), []int{6}
}

func (x *Message) GetAccountKeys() [][]byte {
	if x != nil {
		return x.AccountKeys
	}
	return nil
}

func (x *Message) GetInstructions() []*Instruction {
	if x != nil {
		return x.Instructions
	}
	return nil
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Meta          *Meta                  `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_sniperc_proto_geyserpb_geyser_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_sniperc_proto_geyserpb_geyser_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_sniperc_proto_geyserpb_geyser_proto_rawDescGZIP(), []int{7}
}

func (x *Transaction) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Transaction) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type TransactionUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=Transaction,proto3" json:"Transaction,omitempty"` // ...
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionUpdate) Reset() {
	*x = TransactionUpdate{}
	mi := &file_sniperc_proto_geyserpb_geyser_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionUpdate) ProtoMessage() {}

func (x *TransactionUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_sniperc_proto_geyserpb_geyser_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionUpdate.ProtoReflect.Descriptor instead.
func (*TransactionUpdate) Descriptor() ([]byte, []int) {
	return file_sniperc_proto_geyserpb_geyser_proto_rawDescGZIP(), []int{8}
}

func (x *TransactionUpdate) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

var File_sniperc_proto_geyserpb_geyser_proto protoreflect.FileDescriptor

const file_sniperc_proto_geyserpb_geyser_proto_rawDesc = "" +
	"\n" +
	"#sniperc/proto/geyserpb/geyser.proto\x12\rsniperc.proto\"x\n" +
	"\"SubscribeRequestFilterTransactions\x12\x12\n" +
	"\x04Vote\x18\x01 \x01(\bR\x04Vote\x12\x16\n" +
	"\x06Failed\x18\x02 \x01(\bR\x06Failed\x12&\n" +
	"\x0eAccountInclude\x18\x03 \x03(\tR\x0eAccountInclude\"\x80\x04\n" +
	"\x10SubscribeRequest\x12U\n" +
	"\fTransactions\x18\x01 \x03(\v21.sniperc.proto.SubscribeRequest.TransactionsEntryR\fTransactions\x12g\n" +
	"\x12TransactionsStatus\x18\x02 \x03(\v27.sniperc.proto.SubscribeRequest.TransactionsStatusEntryR\x12TransactionsStatus\x12>\n" +
	"\n" +
	"Commitment\x18\x03 \x01(\x0e2\x1e.sniperc.proto.CommitmentLevelR\n" +
	"Commitment\x1ar\n" +
	"\x11TransactionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12G\n" +
	"\x05value\x18\x02 \x01(\v21.sniperc.proto.SubscribeRequestFilterTransactionsR\x05value:\x028\x01\x1ax\n" +
	"\x17TransactionsStatusEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12G\n" +
	"\x05value\x18\x02 \x01(\v21.sniperc.proto.SubscribeRequestFilterTransactionsR\x05value:\x028\x01\"W\n" +
	"\x11SubscribeResponse\x12B\n" +
	"\vtransaction\x18\x01 \x01(\v2 .sniperc.proto.TransactionUpdateR\vtransaction\"R\n" +
	"\x10InnerInstruction\x12>\n" +
	"\finstructions\x18\x01 \x03(\v2\x1a.sniperc.proto.InstructionR\finstructions\"\xce\x01\n" +
	"\x04Meta\x12:\n" +
	"\x19loaded_writable_addresses\x18\x01 \x03(\fR\x17loadedWritableAddresses\x12:\n" +
	"\x19loaded_readonly_addresses\x18\x02 \x03(\fR\x17loadedReadonlyAddresses\x12N\n" +
	"\x12inner_instructions\x18\x03 \x03(\v2\x1f.sniperc.proto.InnerInstructionR\x11innerInstructions\"e\n" +
	"\vInstruction\x12&\n" +
	"\x0eProgramIdIndex\x18\x01 \x01(\rR\x0eProgramIdIndex\x12\x12\n" +
	"\x04Data\x18\x02 \x01(\fR\x04Data\x12\x1a\n" +
	"\bAccounts\x18\x03 \x03(\rR\bAccounts\"l\n" +
	"\aMessage\x12!\n" +
	"\faccount_keys\x18\x01 \x03(\fR\vaccountKeys\x12>\n" +
	"\finstructions\x18\x02 \x03(\v2\x1a.sniperc.proto.InstructionR\finstructions\"h\n" +
	"\vTransaction\x120\n" +
	"\amessage\x18\x01 \x01(\v2\x16.sniperc.proto.MessageR\amessage\x12'\n" +
	"\x04meta\x18\x02 \x01(\v2\x13.sniperc.proto.MetaR\x04meta\"Q\n" +
	"\x11TransactionUpdate\x12<\n" +
	"\vTransaction\x18\x01 \x01(\v2\x1a.sniperc.proto.TransactionR\vTransaction*>\n" +
	"\x0fCommitmentLevel\x12\r\n" +
	"\tPROCESSED\x10\x00\x12\r\n" +
	"\tCONFIRMED\x10\x01\x12\r\n" +
	"\tFINALIZED\x10\x022\\\n" +
	"\x06Geyser\x12R\n" +
	"\tSubscribe\x12\x1f.sniperc.proto.SubscribeRequest\x1a .sniperc.proto.SubscribeResponse(\x010\x01B\x18Z\x16sniperc/proto/geyserpbb\x06proto3"

var (
	file_sniperc_proto_geyserpb_geyser_proto_rawDescOnce sync.Once
	file_sniperc_proto_geyserpb_geyser_proto_rawDescData []byte
)

func file_sniperc_proto_geyserpb_geyser_proto_rawDescGZIP() []byte {
	file_sniperc_proto_geyserpb_geyser_proto_rawDescOnce.Do(func() {
		file_sniperc_proto_geyserpb_geyser_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sniperc_proto_geyserpb_geyser_proto_rawDesc), len(file_sniperc_proto_geyserpb_geyser_proto_rawDesc)))
	})
	return file_sniperc_proto_geyserpb_geyser_proto_rawDescData
}

var file_sniperc_proto_geyserpb_geyser_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sniperc_proto_geyserpb_geyser_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_sniperc_proto_geyserpb_geyser_proto_goTypes = []any{
	(CommitmentLevel)(0),                       // 0: sniperc.proto.CommitmentLevel
	(*SubscribeRequestFilterTransactions)(nil), // 1: sniperc.proto.SubscribeRequestFilterTransactions
	(*SubscribeRequest)(nil),                   // 2: sniperc.proto.SubscribeRequest
	(*SubscribeResponse)(nil),                  // 3: sniperc.proto.SubscribeResponse
	(*InnerInstruction)(nil),                   // 4: sniperc.proto.InnerInstruction
	(*Meta)(nil),                               // 5: sniperc.proto.Meta
	(*Instruction)(nil),                        // 6: sniperc.proto.Instruction
	(*Message)(nil),                            // 7: sniperc.proto.Message
	(*Transaction)(nil),                        // 8: sniperc.proto.Transaction
	(*TransactionUpdate)(nil),                  // 9: sniperc.proto.TransactionUpdate
	nil,                                        // 10: sniperc.proto.SubscribeRequest.TransactionsEntry
	nil,                                        // 11: sniperc.proto.SubscribeRequest.TransactionsStatusEntry
}
var file_sniperc_proto_geyserpb_geyser_proto_depIdxs = []int32{
	10, // 0: sniperc.proto.SubscribeRequest.Transactions:type_name -> sniperc.proto.SubscribeRequest.TransactionsEntry
	11, // 1: sniperc.proto.SubscribeRequest.TransactionsStatus:type_name -> sniperc.proto.SubscribeRequest.TransactionsStatusEntry
	0,  // 2: sniperc.proto.SubscribeRequest.Commitment:type_name -> sniperc.proto.CommitmentLevel
	9,  // 3: sniperc.proto.SubscribeResponse.transaction:type_name -> sniperc.proto.TransactionUpdate
	6,  // 4: sniperc.proto.InnerInstruction.instructions:type_name -> sniperc.proto.Instruction
	4,  // 5: sniperc.proto.Meta.inner_instructions:type_name -> sniperc.proto.InnerInstruction
	6,  // 6: sniperc.proto.Message.instructions:type_name -> sniperc.proto.Instruction
	7,  // 7: sniperc.proto.Transaction.message:type_name -> sniperc.proto.Message
	5,  // 8: sniperc.proto.Transaction.meta:type_name -> sniperc.proto.Meta
	8,  // 9: sniperc.proto.TransactionUpdate.Transaction:type_name -> sniperc.proto.Transaction
	1,  // 10: sniperc.proto.SubscribeRequest.TransactionsEntry.value:type_name -> sniperc.proto.SubscribeRequestFilterTransactions
	1,  // 11: sniperc.proto.SubscribeRequest.TransactionsStatusEntry.value:type_name -> sniperc.proto.SubscribeRequestFilterTransactions
	2,  // 12: sniperc.proto.Geyser.Subscribe:input_type -> sniperc.proto.SubscribeRequest
	3,  // 13: sniperc.proto.Geyser.Subscribe:output_type -> sniperc.proto.SubscribeResponse
	13, // [13:14] is the sub-list for method output_type
	12, // [12:13] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_sniperc_proto_geyserpb_geyser_proto_init() }
func file_sniperc_proto_geyserpb_geyser_proto_init() {
	if File_sniperc_proto_geyserpb_geyser_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sniperc_proto_geyserpb_geyser_proto_rawDesc), len(file_sniperc_proto_geyserpb_geyser_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sniperc_proto_geyserpb_geyser_proto_goTypes,
		DependencyIndexes: file_sniperc_proto_geyserpb_geyser_proto_depIdxs,
		EnumInfos:         file_sniperc_proto_geyserpb_geyser_proto_enumTypes,
		MessageInfos:      file_sniperc_proto_geyserpb_geyser_proto_msgTypes,
	}.Build()
	File_sniperc_proto_geyserpb_geyser_proto = out.File
	file_sniperc_proto_geyserpb_geyser_proto_goTypes = nil
	file_sniperc_proto_geyserpb_geyser_proto_depIdxs = nil
}
